// SPDX-FileCopyrightText: 2026 Santosh Prabhu Shenbagamoorthy and Santhosh Shyamsundar
// SPDX-License-Identifier: MIT
// Generated by scripts/gen_constants.py from constants/constants.json; edit the table, not this file.
//! The constants of the UMST ecosystem for the Rust runtime: each row's value as the nearest `f64`, its exact
//! rational, provenance and unit, from constants/constants.json, the table Lean, Coq, Agda and Haskell prove.
//! Constants are `const` items: reading one costs nothing at run time.

#![no_std]
#![forbid(unsafe_code)]

/// Provenance of a row: cited (a defining constant or cited value), measured (with standard uncertainty),
/// derived (a theorem in Lean, Coq and Agda from other rows) or policy (a model choice in a proved range).
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Kind {
    Cited,
    Measured,
    Derived,
    Policy,
}

/// One row of the table.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Row {
    pub id: &'static str,
    pub symbol: &'static str,
    pub unit: &'static str,
    pub kind: Kind,
    /// The nearest `f64` to the exact value.
    pub value: f64,
    /// The exact value as a rational of decimal integers.
    pub exact_num: &'static str,
    pub exact_den: &'static str,
    /// Standard uncertainty of a measured row.
    pub uncertainty: Option<f64>,
}

/// ΔνCs: caesium-133 hyperfine transition frequency [Hz]; cited (SI2019).
pub const CAESIUM_HYPERFINE_FREQUENCY: f64 = 9192631770.0;

/// c: speed of light in vacuum [m s⁻¹]; cited (SI2019).
pub const SPEED_OF_LIGHT: f64 = 299792458.0;

/// h: Planck constant [J s]; cited (SI2019).
pub const PLANCK: f64 = 6.62607015e-34;

/// e: elementary charge [C]; cited (SI2019).
pub const ELEMENTARY_CHARGE: f64 = 1.602176634e-19;

/// k_B: Boltzmann constant [J K⁻¹]; cited (SI2019).
pub const BOLTZMANN: f64 = 1.380649e-23;

/// N_A: Avogadro constant [mol⁻¹]; cited (SI2019).
pub const AVOGADRO: f64 = 6.02214076e23;

/// K_cd: luminous efficacy of 540 THz radiation [lm W⁻¹]; cited (SI2019).
pub const LUMINOUS_EFFICACY: f64 = 683.0;

/// R: molar gas constant [J mol⁻¹ K⁻¹]; derived: avogadro * boltzmann.
pub const GAS_CONSTANT: f64 = 8.31446261815324;

/// F: Faraday constant [C mol⁻¹]; derived: avogadro * elementaryCharge.
pub const FARADAY: f64 = 96485.33212331001;

/// c²: mass–energy conversion factor [m² s⁻²]; derived: speedOfLight * speedOfLight.
pub const SPEED_OF_LIGHT_SQUARED: f64 = 8.987551787368176e16;

/// K_J: Josephson constant [Hz V⁻¹]; derived: 2 * elementaryCharge / planck.
pub const JOSEPHSON: f64 = 483597848416983.6;

/// R_K: von Klitzing constant [Ω]; derived: planck / (elementaryCharge * elementaryCharge).
pub const VON_KLITZING: f64 = 25812.807459304506;

/// Φ₀: magnetic flux quantum [Wb]; derived: planck / (2 * elementaryCharge).
pub const FLUX_QUANTUM: f64 = 2.0678338484619295e-15;

/// G₀: conductance quantum [S]; derived: 2 * elementaryCharge * elementaryCharge / planck.
pub const CONDUCTANCE_QUANTUM: f64 = 7.74809172986365e-5;

/// α: fine-structure constant [1]; measured (CODATA2022).
pub const FINE_STRUCTURE: f64 = 0.0072973525643;

/// m_e: electron mass [kg]; measured (CODATA2022).
pub const ELECTRON_MASS: f64 = 9.1093837139e-31;

/// R∞: Rydberg constant [m^-1]; derived: fineStructure * fineStructure * electronMass * speedOfLight / (2 * planck).
pub const RYDBERG: f64 = 10973731.568038493;

/// E_h: Hartree energy [J]; derived: fineStructure * fineStructure * electronMass * speedOfLight * speedOfLight.
pub const HARTREE_ENERGY: f64 = 4.359744722158896e-18;

/// λ_C: Compton wavelength [m]; derived: planck / (electronMass * speedOfLight).
pub const COMPTON_WAVELENGTH: f64 = 2.426310235380317e-12;

/// ε₀: vacuum electric permittivity [F m⁻¹]; derived: elementaryCharge * elementaryCharge / (2 * fineStructure * planck * speedOfLight).
pub const VACUUM_PERMITTIVITY: f64 = 8.85418781884006e-12;

/// μ₀: vacuum magnetic permeability [N A⁻²]; derived: 2 * fineStructure * planck / (elementaryCharge * elementaryCharge * speedOfLight).
pub const VACUUM_PERMEABILITY: f64 = 1.2566370612628147e-6;

/// w_n: non-evaporable water at complete hydration (Powers' model) [kg per kg cement]; cited (Bentz2009).
pub const NON_EVAPORABLE_WATER: f64 = 0.23;

/// w_cs: chemical shrinkage at complete hydration (Powers' model) [kg water per kg cement]; cited (Bentz2009).
pub const CHEMICAL_SHRINKAGE: f64 = 0.064;

/// w_g: gel water at complete hydration (Powers' model) [kg per kg cement]; cited (Bentz2009).
pub const GEL_WATER: f64 = 0.19;

/// ρ_w: density of water assigned in Powers' model [kg m⁻³]; cited (Bentz2009).
pub const WATER_DENSITY: f64 = 1000.0;

/// ρ_c: density of cement assigned in Powers' model [kg m⁻³]; cited (Bentz2009).
pub const CEMENT_DENSITY: f64 = 3150.0;

/// (w/c)*: water-cement ratio at which sealed paste just hydrates completely [1]; derived: nonEvaporableWater + gelWater.
pub const CRITICAL_WC_SEALED: f64 = 0.42;

/// (w/c)_s: water-cement ratio below which space limits complete hydration [1]; derived: nonEvaporableWater + gelWater - chemicalShrinkage.
pub const CRITICAL_WC_SPACE: f64 = 0.356;

/// ρ_c/ρ_w: specific gravity of cement in Powers' model [1]; derived: cementDensity / waterDensity.
pub const DENSITY_RATIO: f64 = 3.15;

/// v_cs: chemical-shrinkage volume per volume of cement reacted [1]; derived: chemicalShrinkage * densityRatio.
pub const SHRINKAGE_VOLUME: f64 = 0.2016;

/// v_gw: gel-water volume per volume of cement reacted [1]; derived: gelWater * densityRatio.
pub const GEL_WATER_VOLUME: f64 = 0.5985;

/// v_cw: capillary water consumed per volume of cement reacted [1]; derived: criticalWcSealed * densityRatio.
pub const CAPILLARY_CONSUMPTION: f64 = 1.323;

/// w_n − w_cs: water bound into gel solids per mass of cement reacted [kg per kg cement]; derived: nonEvaporableWater - chemicalShrinkage.
pub const BOUND_WATER: f64 = 0.166;

/// v_b: volume of water bound into gel solids per volume of cement reacted [1]; derived: boundWater * densityRatio.
pub const BOUND_WATER_VOLUME: f64 = 0.5229;

/// v_gs: gel-solids volume per volume of cement reacted [1]; derived: 1 + boundWaterVolume.
pub const GEL_SOLIDS_VOLUME: f64 = 1.5229;

/// A: intrinsic strength of the gel in Powers' gel-space law [MPa]; cited (Powers1958).
pub const POWERS_GEL_STRENGTH: f64 = 234.0;

/// n: exponent of Powers' gel-space law [1]; cited (Powers1958).
pub const POWERS_GEL_EXPONENT: f64 = 3.0;

/// Q_C3S: heat released by complete hydration of tricalcium silicate (alite) [J/g]; measured (Taylor1997).
pub const HYDRATION_HEAT_C3S: f64 = 517.0;

/// Q_C2S: heat released by complete hydration of dicalcium silicate (belite) [J/g]; cited (Taylor1997).
pub const HYDRATION_HEAT_C2S: f64 = 262.0;

/// Q_C3A,AFm: heat released by complete hydration of tricalcium aluminate to AFm [J/g]; cited (Taylor1997).
pub const HYDRATION_HEAT_C3ATO_AFM: f64 = 1144.0;

/// Q_C3A,AFt: heat released by complete hydration of tricalcium aluminate to AFt [J/g]; cited (Taylor1997).
pub const HYDRATION_HEAT_C3ATO_AFT: f64 = 1672.0;

/// Q_C4AF: heat released by complete hydration of tetracalcium aluminoferrite [J/g]; cited (Taylor1997).
pub const HYDRATION_HEAT_C4AF: f64 = 418.0;

/// Q_hyd: heat of complete hydration of a portland cement (model default) [J/g]; policy: a cement's heat of complete hydration is the mass-weighted sum of its phases' heats, so for a clinker of the four phases it lies between the least and the greatest phase heat; 450 is the gate's default for an unspecified portland cement.
pub const HYDRATION_HEAT_DEFAULT: f64 = 450.0;

/// The policy HYDRATION_HEAT_DEFAULT lies in its range [HYDRATION_HEAT_C2S, HYDRATION_HEAT_C3ATO_AFT], checked at compile time.
const _: () = assert!(
    HYDRATION_HEAT_C2S <= HYDRATION_HEAT_DEFAULT
        && HYDRATION_HEAT_DEFAULT <= HYDRATION_HEAT_C3ATO_AFT
);

/// Every row, in table order.
pub const ROWS: &[Row] = &[
    Row {
        id: "caesiumHyperfineFrequency",
        symbol: "ΔνCs",
        unit: "Hz",
        kind: Kind::Cited,
        value: CAESIUM_HYPERFINE_FREQUENCY,
        exact_num: "9192631770",
        exact_den: "1",
        uncertainty: None,
    },
    Row {
        id: "speedOfLight",
        symbol: "c",
        unit: "m s⁻¹",
        kind: Kind::Cited,
        value: SPEED_OF_LIGHT,
        exact_num: "299792458",
        exact_den: "1",
        uncertainty: None,
    },
    Row {
        id: "planck",
        symbol: "h",
        unit: "J s",
        kind: Kind::Cited,
        value: PLANCK,
        exact_num: "132521403",
        exact_den: "200000000000000000000000000000000000000000",
        uncertainty: None,
    },
    Row {
        id: "elementaryCharge",
        symbol: "e",
        unit: "C",
        kind: Kind::Cited,
        value: ELEMENTARY_CHARGE,
        exact_num: "801088317",
        exact_den: "5000000000000000000000000000",
        uncertainty: None,
    },
    Row {
        id: "boltzmann",
        symbol: "k_B",
        unit: "J K⁻¹",
        kind: Kind::Cited,
        value: BOLTZMANN,
        exact_num: "1380649",
        exact_den: "100000000000000000000000000000",
        uncertainty: None,
    },
    Row {
        id: "avogadro",
        symbol: "N_A",
        unit: "mol⁻¹",
        kind: Kind::Cited,
        value: AVOGADRO,
        exact_num: "602214076000000000000000",
        exact_den: "1",
        uncertainty: None,
    },
    Row {
        id: "luminousEfficacy",
        symbol: "K_cd",
        unit: "lm W⁻¹",
        kind: Kind::Cited,
        value: LUMINOUS_EFFICACY,
        exact_num: "683",
        exact_den: "1",
        uncertainty: None,
    },
    Row {
        id: "gasConstant",
        symbol: "R",
        unit: "J mol⁻¹ K⁻¹",
        kind: Kind::Derived,
        value: GAS_CONSTANT,
        exact_num: "207861565453831",
        exact_den: "25000000000000",
        uncertainty: None,
    },
    Row {
        id: "faraday",
        symbol: "F",
        unit: "C mol⁻¹",
        kind: Kind::Derived,
        value: FARADAY,
        exact_num: "120606665154137523",
        exact_den: "1250000000000",
        uncertainty: None,
    },
    Row {
        id: "speedOfLightSquared",
        symbol: "c²",
        unit: "m² s⁻²",
        kind: Kind::Derived,
        value: SPEED_OF_LIGHT_SQUARED,
        exact_num: "89875517873681764",
        exact_den: "1",
        uncertainty: None,
    },
    Row {
        id: "josephson",
        symbol: "K_J",
        unit: "Hz V⁻¹",
        kind: Kind::Derived,
        value: JOSEPHSON,
        exact_num: "21362355120000000000000",
        exact_den: "44173801",
        uncertainty: None,
    },
    Row {
        id: "vonKlitzing",
        symbol: "R_K",
        unit: "Ω",
        kind: Kind::Derived,
        value: VON_KLITZING,
        exact_num: "5521725125000000000000",
        exact_den: "213914163877964163",
        uncertainty: None,
    },
    Row {
        id: "fluxQuantum",
        symbol: "Φ₀",
        unit: "Wb",
        kind: Kind::Derived,
        value: FLUX_QUANTUM,
        exact_num: "44173801",
        exact_den: "21362355120000000000000",
        uncertainty: None,
    },
    Row {
        id: "conductanceQuantum",
        symbol: "G₀",
        unit: "S",
        kind: Kind::Derived,
        value: CONDUCTANCE_QUANTUM,
        exact_num: "213914163877964163",
        exact_den: "2760862562500000000000",
        uncertainty: None,
    },
    Row {
        id: "fineStructure",
        symbol: "α",
        unit: "1",
        kind: Kind::Measured,
        value: FINE_STRUCTURE,
        exact_num: "72973525643",
        exact_den: "10000000000000",
        uncertainty: Some(1.1e-12),
    },
    Row {
        id: "electronMass",
        symbol: "m_e",
        unit: "kg",
        kind: Kind::Measured,
        value: ELECTRON_MASS,
        exact_num: "91093837139",
        exact_den: "100000000000000000000000000000000000000000",
        uncertainty: Some(2.8e-40),
    },
    Row {
        id: "rydberg",
        symbol: "R∞",
        unit: "m^-1",
        kind: Kind::Derived,
        value: RYDBERG,
        exact_num: "10387530739584650529984309579749063654017",
        exact_den: "946581450000000000000000000000000",
        uncertainty: None,
    },
    Row {
        id: "hartreeEnergy",
        symbol: "E_h",
        unit: "J",
        kind: Kind::Derived,
        value: HARTREE_ENERGY,
        exact_num: "10899361805397240985092496046210715856126763013251",
        exact_den: "2500000000000000000000000000000000000000000000000000000000000000000",
        uncertainty: None,
    },
    Row {
        id: "comptonWavelength",
        symbol: "λ_C",
        unit: "m",
        kind: Kind::Derived,
        value: COMPTON_WAVELENGTH,
        exact_num: "18931629",
        exact_den: "7802641527014999332",
        uncertainty: None,
    },
    Row {
        id: "vacuumPermittivity",
        symbol: "ε₀",
        unit: "F m⁻¹",
        kind: Kind::Derived,
        value: VACUUM_PERMITTIVITY,
        exact_num: "213914163877964163",
        exact_den: "24159659615848077226571442350",
        uncertainty: None,
    },
    Row {
        id: "vacuumPermeability",
        symbol: "μ₀",
        unit: "N A⁻²",
        kind: Kind::Derived,
        value: VACUUM_PERMEABILITY,
        exact_num: "11512564285793853725",
        exact_den: "9161407569998526923097522",
        uncertainty: None,
    },
    Row {
        id: "nonEvaporableWater",
        symbol: "w_n",
        unit: "kg per kg cement",
        kind: Kind::Cited,
        value: NON_EVAPORABLE_WATER,
        exact_num: "23",
        exact_den: "100",
        uncertainty: None,
    },
    Row {
        id: "chemicalShrinkage",
        symbol: "w_cs",
        unit: "kg water per kg cement",
        kind: Kind::Cited,
        value: CHEMICAL_SHRINKAGE,
        exact_num: "8",
        exact_den: "125",
        uncertainty: None,
    },
    Row {
        id: "gelWater",
        symbol: "w_g",
        unit: "kg per kg cement",
        kind: Kind::Cited,
        value: GEL_WATER,
        exact_num: "19",
        exact_den: "100",
        uncertainty: None,
    },
    Row {
        id: "waterDensity",
        symbol: "ρ_w",
        unit: "kg m⁻³",
        kind: Kind::Cited,
        value: WATER_DENSITY,
        exact_num: "1000",
        exact_den: "1",
        uncertainty: None,
    },
    Row {
        id: "cementDensity",
        symbol: "ρ_c",
        unit: "kg m⁻³",
        kind: Kind::Cited,
        value: CEMENT_DENSITY,
        exact_num: "3150",
        exact_den: "1",
        uncertainty: None,
    },
    Row {
        id: "criticalWcSealed",
        symbol: "(w/c)*",
        unit: "1",
        kind: Kind::Derived,
        value: CRITICAL_WC_SEALED,
        exact_num: "21",
        exact_den: "50",
        uncertainty: None,
    },
    Row {
        id: "criticalWcSpace",
        symbol: "(w/c)_s",
        unit: "1",
        kind: Kind::Derived,
        value: CRITICAL_WC_SPACE,
        exact_num: "89",
        exact_den: "250",
        uncertainty: None,
    },
    Row {
        id: "densityRatio",
        symbol: "ρ_c/ρ_w",
        unit: "1",
        kind: Kind::Derived,
        value: DENSITY_RATIO,
        exact_num: "63",
        exact_den: "20",
        uncertainty: None,
    },
    Row {
        id: "shrinkageVolume",
        symbol: "v_cs",
        unit: "1",
        kind: Kind::Derived,
        value: SHRINKAGE_VOLUME,
        exact_num: "126",
        exact_den: "625",
        uncertainty: None,
    },
    Row {
        id: "gelWaterVolume",
        symbol: "v_gw",
        unit: "1",
        kind: Kind::Derived,
        value: GEL_WATER_VOLUME,
        exact_num: "1197",
        exact_den: "2000",
        uncertainty: None,
    },
    Row {
        id: "capillaryConsumption",
        symbol: "v_cw",
        unit: "1",
        kind: Kind::Derived,
        value: CAPILLARY_CONSUMPTION,
        exact_num: "1323",
        exact_den: "1000",
        uncertainty: None,
    },
    Row {
        id: "boundWater",
        symbol: "w_n − w_cs",
        unit: "kg per kg cement",
        kind: Kind::Derived,
        value: BOUND_WATER,
        exact_num: "83",
        exact_den: "500",
        uncertainty: None,
    },
    Row {
        id: "boundWaterVolume",
        symbol: "v_b",
        unit: "1",
        kind: Kind::Derived,
        value: BOUND_WATER_VOLUME,
        exact_num: "5229",
        exact_den: "10000",
        uncertainty: None,
    },
    Row {
        id: "gelSolidsVolume",
        symbol: "v_gs",
        unit: "1",
        kind: Kind::Derived,
        value: GEL_SOLIDS_VOLUME,
        exact_num: "15229",
        exact_den: "10000",
        uncertainty: None,
    },
    Row {
        id: "powersGelStrength",
        symbol: "A",
        unit: "MPa",
        kind: Kind::Cited,
        value: POWERS_GEL_STRENGTH,
        exact_num: "234",
        exact_den: "1",
        uncertainty: None,
    },
    Row {
        id: "powersGelExponent",
        symbol: "n",
        unit: "1",
        kind: Kind::Cited,
        value: POWERS_GEL_EXPONENT,
        exact_num: "3",
        exact_den: "1",
        uncertainty: None,
    },
    Row {
        id: "hydrationHeatC3S",
        symbol: "Q_C3S",
        unit: "J/g",
        kind: Kind::Measured,
        value: HYDRATION_HEAT_C3S,
        exact_num: "517",
        exact_den: "1",
        uncertainty: Some(13.0),
    },
    Row {
        id: "hydrationHeatC2S",
        symbol: "Q_C2S",
        unit: "J/g",
        kind: Kind::Cited,
        value: HYDRATION_HEAT_C2S,
        exact_num: "262",
        exact_den: "1",
        uncertainty: None,
    },
    Row {
        id: "hydrationHeatC3AtoAFm",
        symbol: "Q_C3A,AFm",
        unit: "J/g",
        kind: Kind::Cited,
        value: HYDRATION_HEAT_C3ATO_AFM,
        exact_num: "1144",
        exact_den: "1",
        uncertainty: None,
    },
    Row {
        id: "hydrationHeatC3AtoAFt",
        symbol: "Q_C3A,AFt",
        unit: "J/g",
        kind: Kind::Cited,
        value: HYDRATION_HEAT_C3ATO_AFT,
        exact_num: "1672",
        exact_den: "1",
        uncertainty: None,
    },
    Row {
        id: "hydrationHeatC4AF",
        symbol: "Q_C4AF",
        unit: "J/g",
        kind: Kind::Cited,
        value: HYDRATION_HEAT_C4AF,
        exact_num: "418",
        exact_den: "1",
        uncertainty: None,
    },
    Row {
        id: "hydrationHeatDefault",
        symbol: "Q_hyd",
        unit: "J/g",
        kind: Kind::Policy,
        value: HYDRATION_HEAT_DEFAULT,
        exact_num: "450",
        exact_den: "1",
        uncertainty: None,
    },
];

#[cfg(test)]
#[rustfmt::skip] // generated: one assertion per row
mod tests {
    use super::*;

    fn close(a: f64, b: f64) -> bool {
        (a - b).abs() <= 8.0 * f64::EPSILON * a.abs().max(b.abs())
    }

    /// Each derived row equals its formula evaluated on the rows it reads.
    #[test]
    fn derived_rows_follow_their_formulas() {
        assert!(close(GAS_CONSTANT, AVOGADRO * BOLTZMANN), "gasConstant");
        assert!(close(FARADAY, AVOGADRO * ELEMENTARY_CHARGE), "faraday");
        assert!(close(SPEED_OF_LIGHT_SQUARED, SPEED_OF_LIGHT * SPEED_OF_LIGHT), "speedOfLightSquared");
        assert!(close(JOSEPHSON, 2.0 * ELEMENTARY_CHARGE / PLANCK), "josephson");
        assert!(close(VON_KLITZING, PLANCK / (ELEMENTARY_CHARGE * ELEMENTARY_CHARGE)), "vonKlitzing");
        assert!(close(FLUX_QUANTUM, PLANCK / (2.0 * ELEMENTARY_CHARGE)), "fluxQuantum");
        assert!(close(CONDUCTANCE_QUANTUM, 2.0 * ELEMENTARY_CHARGE * ELEMENTARY_CHARGE / PLANCK), "conductanceQuantum");
        assert!(close(RYDBERG, FINE_STRUCTURE * FINE_STRUCTURE * ELECTRON_MASS * SPEED_OF_LIGHT / (2.0 * PLANCK)), "rydberg");
        assert!(close(HARTREE_ENERGY, FINE_STRUCTURE * FINE_STRUCTURE * ELECTRON_MASS * SPEED_OF_LIGHT * SPEED_OF_LIGHT), "hartreeEnergy");
        assert!(close(COMPTON_WAVELENGTH, PLANCK / (ELECTRON_MASS * SPEED_OF_LIGHT)), "comptonWavelength");
        assert!(close(VACUUM_PERMITTIVITY, ELEMENTARY_CHARGE * ELEMENTARY_CHARGE / (2.0 * FINE_STRUCTURE * PLANCK * SPEED_OF_LIGHT)), "vacuumPermittivity");
        assert!(close(VACUUM_PERMEABILITY, 2.0 * FINE_STRUCTURE * PLANCK / (ELEMENTARY_CHARGE * ELEMENTARY_CHARGE * SPEED_OF_LIGHT)), "vacuumPermeability");
        assert!(close(CRITICAL_WC_SEALED, NON_EVAPORABLE_WATER + GEL_WATER), "criticalWcSealed");
        assert!(close(CRITICAL_WC_SPACE, NON_EVAPORABLE_WATER + GEL_WATER - CHEMICAL_SHRINKAGE), "criticalWcSpace");
        assert!(close(DENSITY_RATIO, CEMENT_DENSITY / WATER_DENSITY), "densityRatio");
        assert!(close(SHRINKAGE_VOLUME, CHEMICAL_SHRINKAGE * DENSITY_RATIO), "shrinkageVolume");
        assert!(close(GEL_WATER_VOLUME, GEL_WATER * DENSITY_RATIO), "gelWaterVolume");
        assert!(close(CAPILLARY_CONSUMPTION, CRITICAL_WC_SEALED * DENSITY_RATIO), "capillaryConsumption");
        assert!(close(BOUND_WATER, NON_EVAPORABLE_WATER - CHEMICAL_SHRINKAGE), "boundWater");
        assert!(close(BOUND_WATER_VOLUME, BOUND_WATER * DENSITY_RATIO), "boundWaterVolume");
        assert!(close(GEL_SOLIDS_VOLUME, 1.0 + BOUND_WATER_VOLUME), "gelSolidsVolume");
    }

    #[test]
    fn rows_name_each_constant_once() {
        for (i, a) in ROWS.iter().enumerate() {
            for b in &ROWS[i + 1..] {
                assert_ne!(a.id, b.id);
            }
        }
    }
}
