-- SPDX-FileCopyrightText: 2026 Santosh Prabhu Shenbagamoorthy and Santhosh Shyamsundar
-- SPDX-License-Identifier: MIT
-- Generated by scripts/gen_constants.py from constants/constants.json; edit the table, not this file.
-- The second-law bounds of the constants table (twin of Lean/Constants/Bounds.lean): exact endpoints on
-- unnormalised rationals, each bound's theorem re-exported under `<id>-theorem` (a renamed or removed theorem
-- fails this module), and for a bound on a table row its value inside.

module Constants.Bounds where

open import Data.Integer using (+_; -[1+_])
open import Data.Rational.Unnormalised.Base using (ℚᵘ; mkℚᵘ; _≤_; _<_; *≤*; *<*)
open import Data.Product using (_×_; _,_)
open import Relation.Nullary.Decidable using (toWitness)
import Data.Integer.Properties as ℤ
import Constants.SI as SI
import Constants.SecondLawDissipation
import Constants.SecondLawElastic
import Constants.SecondLawElectromagnetic
import Constants.SecondLawRestitution
import Constants.SecondLawSolidInelastic

-- E: an elastic modulus holding a body at a nonzero stress (Young's modulus in uniaxial stress, the shear modulus
-- in pure shear) [Pa] lies in (0, ∞); proved by UMST.Constants.SecondLawElastic.relaxation_modulus_pos
-- (second_law_bound.modulus_pos: a body held at stress σ ≠ 0 by a modulus E ≠ 0 stores σ²/(2E); its passive
-- relaxation under the second law forces E > 0 (Agda: the stored energy ψ is given by 2·E·ψ = σ², σ² a positive
-- rational, and E ≠ 0 follows)).
open Constants.SecondLawElastic public using () renaming (relaxation-modulus-pos to elasticModulusPositive-theorem)
elasticModulusPositive-lower : ℚᵘ
elasticModulusPositive-lower = (mkℚᵘ (+ 0) 0)

-- k: the stiffness of a mode storing ½·k·s² [any unit] lies in [0, ∞); proved by
-- UMST.Constants.SecondLawElastic.relaxation_stiffness_nonneg (second_law_bound.stiffness_nonneg: a mode storing
-- ½·k·s² (s ≠ 0) whose passive relaxation to the natural state obeys the second law (transition case) has k ≥ 0
-- (Agda: the squared strain enters as a positive rational q)).
open Constants.SecondLawElastic public using () renaming (relaxation-stiffness-nonneg to quadraticStiffnessNonneg-theorem)
quadraticStiffnessNonneg-lower : ℚᵘ
quadraticStiffnessNonneg-lower = (mkℚᵘ (+ 0) 0)

-- ν: the Poisson ratio of an isotropic solid with 3K + G > 0 [1] lies in [-1, 1/2]; proved by
-- UMST.Constants.SecondLawElastic.isotropic_poisson_bounds (second_law_bound.isotropic_poisson: an isotropic solid
-- storing ½·K·e² + ½·G·γ² relaxing passively under the second law from every volumetric strain and shear, with 3K +
-- G > 0, has −1 ≤ ν ≤ 1/2 for ν = (3K − 2G)/(2(3K + G)) (Agda: the denominator cleared, −2(3K + G) ≤ 3K − 2G ≤ 3K +
-- G)).
open Constants.SecondLawElastic public using () renaming (isotropic-poisson-bounds to isotropicPoissonRatio-theorem)
isotropicPoissonRatio-lower : ℚᵘ
isotropicPoissonRatio-lower = (mkℚᵘ (-[1+ 0 ]) 0)
isotropicPoissonRatio-upper : ℚᵘ
isotropicPoissonRatio-upper = (mkℚᵘ (+ 1) 1)

-- E: Young's modulus 9KG/(3K + G) of an isotropic solid with 3K + G > 0 [Pa] lies in [0, ∞); proved by
-- UMST.Constants.SecondLawElastic.isotropic_young_nonneg (second_law_bound.isotropic_young: under the same
-- relaxation Young's modulus E = 9KG/(3K + G) is nonnegative (Agda: the denominator cleared, 9·K·G ≥ 0)).
open Constants.SecondLawElastic public using () renaming (isotropic-young-nonneg to isotropicYoungModulusNonneg-theorem)
isotropicYoungModulusNonneg-lower : ℚᵘ
isotropicYoungModulusNonneg-lower = (mkℚᵘ (+ 0) 0)

-- G∞: the relaxed modulus of a standard linear solid (it is also at most the instantaneous modulus G∞ + G₁) [Pa]
-- lies in [0, ∞); proved by UMST.Constants.SecondLawElastic.sls_relaxed_le_instantaneous
-- (second_law_bound.sls_relaxed: a standard linear solid storing ½·G∞·ε² + ½·G₁·ξ² relaxing passively under the
-- second law from every total and arm strain has 0 ≤ G∞ ≤ G∞ + G₁ = G₀).
open Constants.SecondLawElastic public using () renaming (sls-relaxed-le-instantaneous to relaxedModulusNonneg-theorem)
relaxedModulusNonneg-lower : ℚᵘ
relaxedModulusNonneg-lower = (mkℚᵘ (+ 0) 0)

-- c: a dissipation coefficient c in a dissipated energy c·q, q > 0 [any unit] lies in [0, ∞); proved by
-- UMST.Constants.SecondLawDissipation.dissipation_coefficient_nonneg (second_law_bound.dissipation_coefficient: a
-- passive step dissipating c·q (q > 0) out of the free energy obeys the second law (transition case) only when c ≥
-- 0).
open Constants.SecondLawDissipation public using () renaming (dissipation-coefficient-nonneg to dissipationCoefficientNonneg-theorem)
dissipationCoefficientNonneg-lower : ℚᵘ
dissipationCoefficientNonneg-lower = (mkℚᵘ (+ 0) 0)

-- η: a dashpot viscosity [Pa s] lies in [0, ∞); proved by UMST.Constants.SecondLawDissipation.viscosity_nonneg
-- (second_law_bound.viscosity: a dashpot at rate r ≠ 0 over dt > 0 dissipating η·r²·dt obeys the second law only
-- when η ≥ 0 (Agda: r² enters as a positive rational q)).
open Constants.SecondLawDissipation public using () renaming (viscosity-nonneg to viscosityNonneg-theorem)
viscosityNonneg-lower : ℚᵘ
viscosityNonneg-lower = (mkℚᵘ (+ 0) 0)

-- τ₀: the yield stress of a Bingham fluid [Pa] lies in [0, ∞); proved by
-- UMST.Constants.SecondLawDissipation.bingham_nonneg (second_law_bound.bingham: a Bingham fluid dissipating (τ₀·|r|
-- + η_p·r²)·dt that obeys the second law at every rate has τ₀ ≥ 0 and η_p ≥ 0 (Agda: at every positive rate, where
-- |r| = r)).
open Constants.SecondLawDissipation public using () renaming (bingham-nonneg to binghamYieldStressNonneg-theorem)
binghamYieldStressNonneg-lower : ℚᵘ
binghamYieldStressNonneg-lower = (mkℚᵘ (+ 0) 0)

-- η_p: the plastic viscosity of a Bingham fluid [Pa s] lies in [0, ∞); proved by
-- UMST.Constants.SecondLawDissipation.bingham_nonneg (second_law_bound.bingham: a Bingham fluid dissipating (τ₀·|r|
-- + η_p·r²)·dt that obeys the second law at every rate has τ₀ ≥ 0 and η_p ≥ 0 (Agda: at every positive rate, where
-- |r| = r)).
open Constants.SecondLawDissipation public using () renaming (bingham-nonneg to binghamPlasticViscosityNonneg-theorem)
binghamPlasticViscosityNonneg-lower : ℚᵘ
binghamPlasticViscosityNonneg-lower = (mkℚᵘ (+ 0) 0)

-- E″: the loss modulus of a harmonic strain cycle [Pa] lies in [0, ∞); proved by
-- UMST.Constants.SecondLawDissipation.lossModulus_nonneg (second_law_bound.loss_modulus: a harmonic strain cycle
-- dissipating π·E″·ε₀² (ε₀ ≠ 0) obeys the second law only when E″ ≥ 0, and then E″/E′ ≥ 0 for E′ > 0 (Coq, Agda:
-- the cycle measure π·ε₀² enters as a positive rational q)).
open Constants.SecondLawDissipation public using () renaming (lossModulus-nonneg to lossModulusNonneg-theorem)
lossModulusNonneg-lower : ℚᵘ
lossModulusNonneg-lower = (mkℚᵘ (+ 0) 0)

-- e: a coefficient of restitution e ≥ 0 of a passive impact [1] lies in (−∞, 1]; proved by
-- UMST.ConvexPhiChannels.restitution_le_one (second_law_bound.restitution: a passive impact with free energy ½·μ·v²
-- before and ½·μ·(e·v)² after that obeys the second law (transition case) has e ≤ 1 for e ≥ 0 and μ·v² > 0 (Agda:
-- μ·v² enters as a positive rational m)).
open Constants.SecondLawRestitution public using () renaming (restitution-le-one to restitutionAtMostOne-theorem)
restitutionAtMostOne-upper : ℚᵘ
restitutionAtMostOne-upper = (mkℚᵘ (+ 1) 0)

-- ε: the permittivity of a medium storing the field energy ½·ε·E² that relaxes passively from every field [F m⁻¹]
-- lies in [0, ∞); proved by UMST.Constants.SecondLawElectromagnetic.electricRelaxation_secondLaw_iff
-- (second_law_bound.electric_relaxation: a vacuum field storing ½·ε·E² relaxes passively from every field exactly
-- when ε ≥ 0).
open Constants.SecondLawElectromagnetic public using () renaming (electricRelaxation-secondLaw-⇔ to permittivityNonneg-theorem)
permittivityNonneg-lower : ℚᵘ
permittivityNonneg-lower = (mkℚᵘ (+ 0) 0)
permittivityNonneg-admits : (permittivityNonneg-lower ≤ SI.vacuumPermittivity)
permittivityNonneg-admits = *≤* (toWitness {a? = _ ℤ.≤? _} _)

-- μ: the permeability of a medium storing the field energy B²/(2μ) that relaxes passively from every flux density
-- [N A⁻²] lies in (0, ∞); proved by UMST.Constants.SecondLawElectromagnetic.magneticRelaxation_secondLaw_iff
-- (second_law_bound.magnetic_relaxation: a field storing B²/(2μ), μ ≠ 0, relaxes passively from every flux density
-- exactly when μ > 0).
open Constants.SecondLawElectromagnetic public using () renaming (magneticRelaxation-secondLaw-⇔ to permeabilityPositive-theorem)
permeabilityPositive-lower : ℚᵘ
permeabilityPositive-lower = (mkℚᵘ (+ 0) 0)
permeabilityPositive-admits : (permeabilityPositive-lower < SI.vacuumPermeability)
permeabilityPositive-admits = *<* (toWitness {a? = _ ℤ.<? _} _)

-- G: the conductance of a Joule step dissipating G·V²·dt [S] lies in [0, ∞); proved by
-- UMST.Constants.SecondLawElectromagnetic.conductanceDissipation_secondLaw_iff
-- (second_law_bound.conductance_dissipation: every Joule step dissipating G·V²·dt is admitted exactly when the
-- conductance G ≥ 0).
open Constants.SecondLawElectromagnetic public using () renaming (conductanceDissipation-secondLaw-⇔ to conductanceNonneg-theorem)
conductanceNonneg-lower : ℚᵘ
conductanceNonneg-lower = (mkℚᵘ (+ 0) 0)
conductanceNonneg-admits : (conductanceNonneg-lower ≤ SI.conductanceQuantum)
conductanceNonneg-admits = *≤* (toWitness {a? = _ ℤ.≤? _} _)

-- R: the resistance of a Joule step dissipating R·I²·dt [Ω] lies in [0, ∞); proved by
-- UMST.Constants.SecondLawElectromagnetic.resistanceDissipation_secondLaw_iff
-- (second_law_bound.resistance_dissipation: every Joule step dissipating R·I²·dt is admitted exactly when the
-- resistance R ≥ 0).
open Constants.SecondLawElectromagnetic public using () renaming (resistanceDissipation-secondLaw-⇔ to resistanceNonneg-theorem)
resistanceNonneg-lower : ℚᵘ
resistanceNonneg-lower = (mkℚᵘ (+ 0) 0)
resistanceNonneg-admits : (resistanceNonneg-lower ≤ SI.vonKlitzing)
resistanceNonneg-admits = *≤* (toWitness {a? = _ ℤ.≤? _} _)

-- k: the modulus k of a plastic and hardening free energy ½·k·(x² + y² + 2c·x·y) that relaxes from every state [J
-- m⁻³] lies in (0, ∞); proved by UMST.Constants.SecondLawSolidInelastic.coupledWell_bounds
-- (second_law_bound.coupled_well: a plastic strain and a hardening variable storing ½·k·(x² + y² + 2c·x·y) that
-- relax from every (x, y), with k ≠ 0, have k > 0 and −1 ≤ c ≤ 1 (Agda: takes k > 0 and states 0 ≤ 1 + c and 0 ≤ 1
-- − c)).
open Constants.SecondLawSolidInelastic public using () renaming (coupledWell-bounds to coupledWellModulusPositive-theorem)
coupledWellModulusPositive-lower : ℚᵘ
coupledWellModulusPositive-lower = (mkℚᵘ (+ 0) 0)

-- c: the cross coupling c of a plastic and hardening free energy ½·k·(x² + y² + 2c·x·y) that relaxes from every
-- state [1] lies in [-1, 1]; proved by UMST.Constants.SecondLawSolidInelastic.coupledWell_bounds
-- (second_law_bound.coupled_well: a plastic strain and a hardening variable storing ½·k·(x² + y² + 2c·x·y) that
-- relax from every (x, y), with k ≠ 0, have k > 0 and −1 ≤ c ≤ 1 (Agda: takes k > 0 and states 0 ≤ 1 + c and 0 ≤ 1
-- − c)).
open Constants.SecondLawSolidInelastic public using () renaming (coupledWell-bounds to coupledWellCrossCoupling-theorem)
coupledWellCrossCoupling-lower : ℚᵘ
coupledWellCrossCoupling-lower = (mkℚᵘ (-[1+ 0 ]) 0)
coupledWellCrossCoupling-upper : ℚᵘ
coupledWellCrossCoupling-upper = (mkℚᵘ (+ 1) 0)

-- k: the modulus k of a phase-field double well k·φ²·(1 − φ)² that relaxes [J m⁻³] lies in [0, ∞); proved by
-- UMST.Constants.SecondLawSolidInelastic.doubleWell_modulus_nonneg (second_law_bound.double_well: a phase field φ ∉
-- {0, 1} storing k·φ²·(1 − φ)² that relaxes has k ≥ 0 (Agda: the envelope enters as a positive rational q)).
open Constants.SecondLawSolidInelastic public using () renaming (doubleWell-modulus-nonneg to doubleWellModulusNonneg-theorem)
doubleWellModulusNonneg-lower : ℚᵘ
doubleWellModulusNonneg-lower = (mkℚᵘ (+ 0) 0)

-- G_c: the Griffith fracture energy dissipated per unit crack area [J m⁻²] lies in [0, ∞); proved by
-- UMST.Constants.SecondLawSolidInelastic.griffith_fracture_energy_nonneg (second_law_bound.griffith_energy: a crack
-- extension ΔA > 0 dissipating G_c·ΔA obeys the second law only when G_c ≥ 0).
open Constants.SecondLawSolidInelastic public using () renaming (griffith-fracture-energy-nonneg to griffithFractureEnergyNonneg-theorem)
griffithFractureEnergyNonneg-lower : ℚᵘ
griffithFractureEnergyNonneg-lower = (mkℚᵘ (+ 0) 0)

-- K: the fracture toughness K = √(E·G_c) [Pa m^(1/2)] lies in [0, ∞); proved by
-- UMST.Constants.SecondLawSolidInelastic.griffith_toughness_nonneg (second_law_bound.griffith_toughness: with G_c ≥
-- 0 from a crack extension and E > 0 from an elastic relaxation, K = √(E·G_c) ≥ 0 and K² = E·G_c (Coq and Agda: the
-- radicand E·G_c ≥ 0)).
open Constants.SecondLawSolidInelastic public using () renaming (griffith-toughness-nonneg to fractureToughnessNonneg-theorem)
fractureToughnessNonneg-lower : ℚᵘ
fractureToughnessNonneg-lower = (mkℚᵘ (+ 0) 0)

-- A: the Norton creep coefficient A of the rate A·σⁿ, for every exponent n [any unit] lies in [0, ∞); proved by
-- UMST.Constants.SecondLawSolidInelastic.norton_coefficient_nonneg (second_law_bound.norton: steady creep at stress
-- σ > 0 with rate A·σⁿ over dt > 0 dissipates σ·A·σⁿ·dt and obeys the second law only when A ≥ 0 (Coq and Agda: σⁿ
-- enters as a positive rational p)).
open Constants.SecondLawSolidInelastic public using () renaming (norton-coefficient-nonneg to nortonCoefficientNonneg-theorem)
nortonCoefficientNonneg-lower : ℚᵘ
nortonCoefficientNonneg-lower = (mkℚᵘ (+ 0) 0)

-- k_p: the parabolic scaling constant k_p of a scale growing at k_p/(2x) under a positive affinity [m² s⁻¹] lies in
-- [0, ∞); proved by UMST.Constants.SecondLawSolidInelastic.parabolic_rate_nonneg (second_law_bound.parabolic_rate:
-- a scale of thickness x > 0 growing at k_p/(2x) under a reaction affinity a > 0 dissipates a·k_p/(2x)·dt and obeys
-- the second law only when k_p ≥ 0 (Agda: 1/(2x) enters as a positive rational w)).
open Constants.SecondLawSolidInelastic public using () renaming (parabolic-rate-nonneg to parabolicRateConstantNonneg-theorem)
parabolicRateConstantNonneg-lower : ℚᵘ
parabolicRateConstantNonneg-lower = (mkℚᵘ (+ 0) 0)

-- b: the prefactor b of a frictional fibre bond stress b·√f_c [any unit] lies in [0, ∞); proved by
-- UMST.Constants.SecondLawSolidInelastic.frictional_bond_nonneg (second_law_bound.frictional_bond: a fibre with
-- bond stress b·√f_c (f_c > 0) sliding over a slip area s > 0 dissipates b·√f_c·s and obeys the second law only
-- when b ≥ 0 (Coq and Agda: √f_c enters as a positive rational r)).
open Constants.SecondLawSolidInelastic public using () renaming (frictional-bond-nonneg to frictionalBondPrefactorNonneg-theorem)
frictionalBondPrefactorNonneg-lower : ℚᵘ
frictionalBondPrefactorNonneg-lower = (mkℚᵘ (+ 0) 0)
