# SPDX-FileCopyrightText: 2026 Santosh Prabhu Shenbagamoorthy and Santhosh Shyamsundar
# SPDX-License-Identifier: MIT
# W-62: lockfile pins ordered-float <5.5 so CI and root census (rustc 1.88) agree.
[toolchain]
channel = "1.88.0"
