# SPDX-FileCopyrightText: 2026 Santosh Prabhu Shenbagamoorthy and Santhosh Shyamsundar
# SPDX-License-Identifier: MIT
# W-62 git dep on umst-manifold @ ce9828ea pulls ordered-float 5.x (rustc 1.90+).
[toolchain]
channel = "1.90"
