-- SPDX-FileCopyrightText: 2026 Santosh Prabhu Shenbagamoorthy and Santhosh Shyamsundar
-- SPDX-License-Identifier: MIT
/-
  Generated by scripts/gen_constants.py from constants/constants.json; edit the table, not this file.

  The second-law bounds of the constants table. Each bound confines a quantity to an interval with exact
  rational endpoints and names, as `<id>_theorem`, the theorem of formal_parity.json that proves it: a
  renamed or removed theorem fails this module. A bound on a row of the table proves the row's exact value
  lies inside (`<id>_admits`). A bound fixes no value; the value stays cited, measured or chosen.
-/

import Constants.SI
import Constants.SecondLawDissipation
import Constants.SecondLawElastic
import Constants.SecondLawElectromagnetic
import Constants.SecondLawSolidInelastic
import ConvexPhiChannels

namespace UMST.Constants.Bounds

/-- E: an elastic modulus holding a body at a nonzero stress (Young's modulus in uniaxial stress, the shear modulus
    in pure shear) [Pa] lies in (0, ∞); proved by UMST.Constants.SecondLawElastic.relaxation_modulus_pos
    (second_law_bound.modulus_pos: a body held at stress σ ≠ 0 by a modulus E ≠ 0 stores σ²/(2E); its passive
    relaxation under the second law forces E > 0 (Agda: the stored energy ψ is given by 2·E·ψ = σ², σ² a positive
    rational, and E ≠ 0 follows)). -/
def elasticModulusPositive_lower : ℚ := (0 : ℚ)
alias elasticModulusPositive_theorem := UMST.Constants.SecondLawElastic.relaxation_modulus_pos

/-- k: the stiffness of a mode storing ½·k·s² [any unit] lies in [0, ∞); proved by
    UMST.Constants.SecondLawElastic.relaxation_stiffness_nonneg (second_law_bound.stiffness_nonneg: a mode storing
    ½·k·s² (s ≠ 0) whose passive relaxation to the natural state obeys the second law (transition case) has k ≥ 0
    (Agda: the squared strain enters as a positive rational q)). -/
def quadraticStiffnessNonneg_lower : ℚ := (0 : ℚ)
alias quadraticStiffnessNonneg_theorem := UMST.Constants.SecondLawElastic.relaxation_stiffness_nonneg

/-- ν: the Poisson ratio of an isotropic solid with 3K + G > 0 [1] lies in [-1, 1/2]; proved by
    UMST.Constants.SecondLawElastic.isotropic_poisson_bounds (second_law_bound.isotropic_poisson: an isotropic solid
    storing ½·K·e² + ½·G·γ² relaxing passively under the second law from every volumetric strain and shear, with 3K
    + G > 0, has −1 ≤ ν ≤ 1/2 for ν = (3K − 2G)/(2(3K + G)) (Agda: the denominator cleared, −2(3K + G) ≤ 3K − 2G ≤
    3K + G)). -/
def isotropicPoissonRatio_lower : ℚ := (-1 : ℚ)
def isotropicPoissonRatio_upper : ℚ := (1 : ℚ) / 2
alias isotropicPoissonRatio_theorem := UMST.Constants.SecondLawElastic.isotropic_poisson_bounds

/-- E: Young's modulus 9KG/(3K + G) of an isotropic solid with 3K + G > 0 [Pa] lies in [0, ∞); proved by
    UMST.Constants.SecondLawElastic.isotropic_young_nonneg (second_law_bound.isotropic_young: under the same
    relaxation Young's modulus E = 9KG/(3K + G) is nonnegative (Agda: the denominator cleared, 9·K·G ≥ 0)). -/
def isotropicYoungModulusNonneg_lower : ℚ := (0 : ℚ)
alias isotropicYoungModulusNonneg_theorem := UMST.Constants.SecondLawElastic.isotropic_young_nonneg

/-- G∞: the relaxed modulus of a standard linear solid (it is also at most the instantaneous modulus G∞ + G₁) [Pa]
    lies in [0, ∞); proved by UMST.Constants.SecondLawElastic.sls_relaxed_le_instantaneous
    (second_law_bound.sls_relaxed: a standard linear solid storing ½·G∞·ε² + ½·G₁·ξ² relaxing passively under the
    second law from every total and arm strain has 0 ≤ G∞ ≤ G∞ + G₁ = G₀). -/
def relaxedModulusNonneg_lower : ℚ := (0 : ℚ)
alias relaxedModulusNonneg_theorem := UMST.Constants.SecondLawElastic.sls_relaxed_le_instantaneous

/-- c: a dissipation coefficient c in a dissipated energy c·q, q > 0 [any unit] lies in [0, ∞); proved by
    UMST.Constants.SecondLawDissipation.dissipation_coefficient_nonneg (second_law_bound.dissipation_coefficient: a
    passive step dissipating c·q (q > 0) out of the free energy obeys the second law (transition case) only when c ≥
    0). -/
def dissipationCoefficientNonneg_lower : ℚ := (0 : ℚ)
alias dissipationCoefficientNonneg_theorem := UMST.Constants.SecondLawDissipation.dissipation_coefficient_nonneg

/-- η: a dashpot viscosity [Pa s] lies in [0, ∞); proved by UMST.Constants.SecondLawDissipation.viscosity_nonneg
    (second_law_bound.viscosity: a dashpot at rate r ≠ 0 over dt > 0 dissipating η·r²·dt obeys the second law only
    when η ≥ 0 (Agda: r² enters as a positive rational q)). -/
def viscosityNonneg_lower : ℚ := (0 : ℚ)
alias viscosityNonneg_theorem := UMST.Constants.SecondLawDissipation.viscosity_nonneg

/-- τ₀: the yield stress of a Bingham fluid [Pa] lies in [0, ∞); proved by
    UMST.Constants.SecondLawDissipation.bingham_nonneg (second_law_bound.bingham: a Bingham fluid dissipating
    (τ₀·|r| + η_p·r²)·dt that obeys the second law at every rate has τ₀ ≥ 0 and η_p ≥ 0 (Agda: at every positive
    rate, where |r| = r)). -/
def binghamYieldStressNonneg_lower : ℚ := (0 : ℚ)
alias binghamYieldStressNonneg_theorem := UMST.Constants.SecondLawDissipation.bingham_nonneg

/-- η_p: the plastic viscosity of a Bingham fluid [Pa s] lies in [0, ∞); proved by
    UMST.Constants.SecondLawDissipation.bingham_nonneg (second_law_bound.bingham: a Bingham fluid dissipating
    (τ₀·|r| + η_p·r²)·dt that obeys the second law at every rate has τ₀ ≥ 0 and η_p ≥ 0 (Agda: at every positive
    rate, where |r| = r)). -/
def binghamPlasticViscosityNonneg_lower : ℚ := (0 : ℚ)
alias binghamPlasticViscosityNonneg_theorem := UMST.Constants.SecondLawDissipation.bingham_nonneg

/-- E″: the loss modulus of a harmonic strain cycle [Pa] lies in [0, ∞); proved by
    UMST.Constants.SecondLawDissipation.lossModulus_nonneg (second_law_bound.loss_modulus: a harmonic strain cycle
    dissipating π·E″·ε₀² (ε₀ ≠ 0) obeys the second law only when E″ ≥ 0, and then E″/E′ ≥ 0 for E′ > 0 (Coq, Agda:
    the cycle measure π·ε₀² enters as a positive rational q)). -/
def lossModulusNonneg_lower : ℚ := (0 : ℚ)
alias lossModulusNonneg_theorem := UMST.Constants.SecondLawDissipation.lossModulus_nonneg

/-- e: a coefficient of restitution e ≥ 0 of a passive impact [1] lies in (−∞, 1]; proved by
    UMST.ConvexPhiChannels.restitution_le_one (second_law_bound.restitution: a passive impact with free energy
    ½·μ·v² before and ½·μ·(e·v)² after that obeys the second law (transition case) has e ≤ 1 for e ≥ 0 and μ·v² > 0
    (Agda: μ·v² enters as a positive rational m)). -/
def restitutionAtMostOne_upper : ℚ := (1 : ℚ)
alias restitutionAtMostOne_theorem := UMST.ConvexPhiChannels.restitution_le_one

/-- ε: the permittivity of a medium storing the field energy ½·ε·E² that relaxes passively from every field [F m⁻¹]
    lies in [0, ∞); proved by UMST.Constants.SecondLawElectromagnetic.electricRelaxation_secondLaw_iff
    (second_law_bound.electric_relaxation: a vacuum field storing ½·ε·E² relaxes passively from every field exactly
    when ε ≥ 0). -/
def permittivityNonneg_lower : ℚ := (0 : ℚ)
alias permittivityNonneg_theorem := UMST.Constants.SecondLawElectromagnetic.electricRelaxation_secondLaw_iff

/-- The table's vacuumPermittivity lies in the bound. -/
theorem permittivityNonneg_admits :
    permittivityNonneg_lower ≤ UMST.Constants.SI.vacuumPermittivity := by
  rw [UMST.Constants.SI.vacuumPermittivity_value]; norm_num [permittivityNonneg_lower]

/-- μ: the permeability of a medium storing the field energy B²/(2μ) that relaxes passively from every flux density
    [N A⁻²] lies in (0, ∞); proved by UMST.Constants.SecondLawElectromagnetic.magneticRelaxation_secondLaw_iff
    (second_law_bound.magnetic_relaxation: a field storing B²/(2μ), μ ≠ 0, relaxes passively from every flux density
    exactly when μ > 0). -/
def permeabilityPositive_lower : ℚ := (0 : ℚ)
alias permeabilityPositive_theorem := UMST.Constants.SecondLawElectromagnetic.magneticRelaxation_secondLaw_iff

/-- The table's vacuumPermeability lies in the bound. -/
theorem permeabilityPositive_admits :
    permeabilityPositive_lower < UMST.Constants.SI.vacuumPermeability := by
  rw [UMST.Constants.SI.vacuumPermeability_value]; norm_num [permeabilityPositive_lower]

/-- G: the conductance of a Joule step dissipating G·V²·dt [S] lies in [0, ∞); proved by
    UMST.Constants.SecondLawElectromagnetic.conductanceDissipation_secondLaw_iff
    (second_law_bound.conductance_dissipation: every Joule step dissipating G·V²·dt is admitted exactly when the
    conductance G ≥ 0). -/
def conductanceNonneg_lower : ℚ := (0 : ℚ)
alias conductanceNonneg_theorem := UMST.Constants.SecondLawElectromagnetic.conductanceDissipation_secondLaw_iff

/-- The table's conductanceQuantum lies in the bound. -/
theorem conductanceNonneg_admits :
    conductanceNonneg_lower ≤ UMST.Constants.SI.conductanceQuantum := by
  rw [UMST.Constants.SI.conductanceQuantum_value]; norm_num [conductanceNonneg_lower]

/-- R: the resistance of a Joule step dissipating R·I²·dt [Ω] lies in [0, ∞); proved by
    UMST.Constants.SecondLawElectromagnetic.resistanceDissipation_secondLaw_iff
    (second_law_bound.resistance_dissipation: every Joule step dissipating R·I²·dt is admitted exactly when the
    resistance R ≥ 0). -/
def resistanceNonneg_lower : ℚ := (0 : ℚ)
alias resistanceNonneg_theorem := UMST.Constants.SecondLawElectromagnetic.resistanceDissipation_secondLaw_iff

/-- The table's vonKlitzing lies in the bound. -/
theorem resistanceNonneg_admits :
    resistanceNonneg_lower ≤ UMST.Constants.SI.vonKlitzing := by
  rw [UMST.Constants.SI.vonKlitzing_value]; norm_num [resistanceNonneg_lower]

/-- k: the modulus k of a plastic and hardening free energy ½·k·(x² + y² + 2c·x·y) that relaxes from every state [J
    m⁻³] lies in (0, ∞); proved by UMST.Constants.SecondLawSolidInelastic.coupledWell_bounds
    (second_law_bound.coupled_well: a plastic strain and a hardening variable storing ½·k·(x² + y² + 2c·x·y) that
    relax from every (x, y), with k ≠ 0, have k > 0 and −1 ≤ c ≤ 1 (Agda: takes k > 0 and states 0 ≤ 1 + c and 0 ≤ 1
    − c)). -/
def coupledWellModulusPositive_lower : ℚ := (0 : ℚ)
alias coupledWellModulusPositive_theorem := UMST.Constants.SecondLawSolidInelastic.coupledWell_bounds

/-- c: the cross coupling c of a plastic and hardening free energy ½·k·(x² + y² + 2c·x·y) that relaxes from every
    state [1] lies in [-1, 1]; proved by UMST.Constants.SecondLawSolidInelastic.coupledWell_bounds
    (second_law_bound.coupled_well: a plastic strain and a hardening variable storing ½·k·(x² + y² + 2c·x·y) that
    relax from every (x, y), with k ≠ 0, have k > 0 and −1 ≤ c ≤ 1 (Agda: takes k > 0 and states 0 ≤ 1 + c and 0 ≤ 1
    − c)). -/
def coupledWellCrossCoupling_lower : ℚ := (-1 : ℚ)
def coupledWellCrossCoupling_upper : ℚ := (1 : ℚ)
alias coupledWellCrossCoupling_theorem := UMST.Constants.SecondLawSolidInelastic.coupledWell_bounds

/-- k: the modulus k of a phase-field double well k·φ²·(1 − φ)² that relaxes [J m⁻³] lies in [0, ∞); proved by
    UMST.Constants.SecondLawSolidInelastic.doubleWell_modulus_nonneg (second_law_bound.double_well: a phase field φ
    ∉ {0, 1} storing k·φ²·(1 − φ)² that relaxes has k ≥ 0 (Agda: the envelope enters as a positive rational q)). -/
def doubleWellModulusNonneg_lower : ℚ := (0 : ℚ)
alias doubleWellModulusNonneg_theorem := UMST.Constants.SecondLawSolidInelastic.doubleWell_modulus_nonneg

/-- G_c: the Griffith fracture energy dissipated per unit crack area [J m⁻²] lies in [0, ∞); proved by
    UMST.Constants.SecondLawSolidInelastic.griffith_fracture_energy_nonneg (second_law_bound.griffith_energy: a
    crack extension ΔA > 0 dissipating G_c·ΔA obeys the second law only when G_c ≥ 0). -/
def griffithFractureEnergyNonneg_lower : ℚ := (0 : ℚ)
alias griffithFractureEnergyNonneg_theorem := UMST.Constants.SecondLawSolidInelastic.griffith_fracture_energy_nonneg

/-- K: the fracture toughness K = √(E·G_c) [Pa m^(1/2)] lies in [0, ∞); proved by
    UMST.Constants.SecondLawSolidInelastic.griffith_toughness_nonneg (second_law_bound.griffith_toughness: with G_c
    ≥ 0 from a crack extension and E > 0 from an elastic relaxation, K = √(E·G_c) ≥ 0 and K² = E·G_c (Coq and Agda:
    the radicand E·G_c ≥ 0)). -/
def fractureToughnessNonneg_lower : ℚ := (0 : ℚ)
alias fractureToughnessNonneg_theorem := UMST.Constants.SecondLawSolidInelastic.griffith_toughness_nonneg

/-- A: the Norton creep coefficient A of the rate A·σⁿ, for every exponent n [any unit] lies in [0, ∞); proved by
    UMST.Constants.SecondLawSolidInelastic.norton_coefficient_nonneg (second_law_bound.norton: steady creep at
    stress σ > 0 with rate A·σⁿ over dt > 0 dissipates σ·A·σⁿ·dt and obeys the second law only when A ≥ 0 (Coq and
    Agda: σⁿ enters as a positive rational p)). -/
def nortonCoefficientNonneg_lower : ℚ := (0 : ℚ)
alias nortonCoefficientNonneg_theorem := UMST.Constants.SecondLawSolidInelastic.norton_coefficient_nonneg

/-- k_p: the parabolic scaling constant k_p of a scale growing at k_p/(2x) under a positive affinity [m² s⁻¹] lies
    in [0, ∞); proved by UMST.Constants.SecondLawSolidInelastic.parabolic_rate_nonneg
    (second_law_bound.parabolic_rate: a scale of thickness x > 0 growing at k_p/(2x) under a reaction affinity a > 0
    dissipates a·k_p/(2x)·dt and obeys the second law only when k_p ≥ 0 (Agda: 1/(2x) enters as a positive rational
    w)). -/
def parabolicRateConstantNonneg_lower : ℚ := (0 : ℚ)
alias parabolicRateConstantNonneg_theorem := UMST.Constants.SecondLawSolidInelastic.parabolic_rate_nonneg

/-- b: the prefactor b of a frictional fibre bond stress b·√f_c [any unit] lies in [0, ∞); proved by
    UMST.Constants.SecondLawSolidInelastic.frictional_bond_nonneg (second_law_bound.frictional_bond: a fibre with
    bond stress b·√f_c (f_c > 0) sliding over a slip area s > 0 dissipates b·√f_c·s and obeys the second law only
    when b ≥ 0 (Coq and Agda: √f_c enters as a positive rational r)). -/
def frictionalBondPrefactorNonneg_lower : ℚ := (0 : ℚ)
alias frictionalBondPrefactorNonneg_theorem := UMST.Constants.SecondLawSolidInelastic.frictional_bond_nonneg

end UMST.Constants.Bounds
