-- SPDX-FileCopyrightText: 2026 Santosh Prabhu Shenbagamoorthy and Santhosh Shyamsundar
-- SPDX-License-Identifier: MIT
/-
  Generated by scripts/gen_constants.py from constants/constants.json; edit the table, not this file.

  The constants of the UMST ecosystem as exact rationals: the seven defining constants of the SI (cited),
  cited measurements with their standard uncertainty, and constants derived from them, each with its exact
  value and its defining equation proved by computation. `Constants.SIBridge` identifies these values with
  the real-valued constants of the Landauer chain and states the laws that carry the second law.
-/

import Mathlib.Tactic.NormNum
import Mathlib.Algebra.Order.Group.Abs

namespace UMST.Constants.SI

/-- ΔνCs: caesium-133 hyperfine transition frequency [Hz]; cited: BIPM, The International System of Units (SI), 9th edition (2019), Table 1. -/
def caesiumHyperfineFrequency : ℚ := (9192631770 : ℚ)

/-- c: speed of light in vacuum [m s⁻¹]; cited: BIPM, The International System of Units (SI), 9th edition (2019), Table 1. -/
def speedOfLight : ℚ := (299792458 : ℚ)

/-- h: Planck constant [J s]; cited: BIPM, The International System of Units (SI), 9th edition (2019), Table 1. -/
def planck : ℚ := (132521403 : ℚ) / 200000000000000000000000000000000000000000

/-- e: elementary charge [C]; cited: BIPM, The International System of Units (SI), 9th edition (2019), Table 1. -/
def elementaryCharge : ℚ := (801088317 : ℚ) / 5000000000000000000000000000

/-- k_B: Boltzmann constant [J K⁻¹]; cited: BIPM, The International System of Units (SI), 9th edition (2019), Table 1. -/
def boltzmann : ℚ := (1380649 : ℚ) / 100000000000000000000000000000

/-- N_A: Avogadro constant [mol⁻¹]; cited: BIPM, The International System of Units (SI), 9th edition (2019), Table 1. -/
def avogadro : ℚ := (602214076000000000000000 : ℚ)

/-- K_cd: luminous efficacy of 540 THz radiation [lm W⁻¹]; cited: BIPM, The International System of Units (SI), 9th edition (2019), Table 1. -/
def luminousEfficacy : ℚ := (683 : ℚ)

/-- R: molar gas constant [J mol⁻¹ K⁻¹]; derived: avogadro * boltzmann. -/
def gasConstant : ℚ := avogadro * boltzmann

theorem gasConstant_value : gasConstant = (207861565453831 : ℚ) / 25000000000000 := by
  norm_num [gasConstant, boltzmann, avogadro]

/-- F: Faraday constant [C mol⁻¹]; derived: avogadro * elementaryCharge. -/
def faraday : ℚ := avogadro * elementaryCharge

theorem faraday_value : faraday = (120606665154137523 : ℚ) / 1250000000000 := by
  norm_num [faraday, elementaryCharge, avogadro]

/-- c²: mass–energy conversion factor [m² s⁻²]; derived: speedOfLight * speedOfLight. -/
def speedOfLightSquared : ℚ := speedOfLight * speedOfLight

theorem speedOfLightSquared_value : speedOfLightSquared = (89875517873681764 : ℚ) := by
  norm_num [speedOfLightSquared, speedOfLight]

/-- K_J: Josephson constant [Hz V⁻¹]; derived: 2 * elementaryCharge / planck. -/
def josephson : ℚ := 2 * elementaryCharge / planck

theorem josephson_value : josephson = (21362355120000000000000 : ℚ) / 44173801 := by
  norm_num [josephson, planck, elementaryCharge]

theorem josephson_derivation : (21362355120000000000000 : ℚ) / 44173801 * (planck) = 2 * elementaryCharge := by
  norm_num [planck, elementaryCharge]

/-- R_K: von Klitzing constant [Ω]; derived: planck / (elementaryCharge * elementaryCharge). -/
def vonKlitzing : ℚ := planck / (elementaryCharge * elementaryCharge)

theorem vonKlitzing_value : vonKlitzing = (5521725125000000000000 : ℚ) / 213914163877964163 := by
  norm_num [vonKlitzing, planck, elementaryCharge]

theorem vonKlitzing_derivation : (5521725125000000000000 : ℚ) / 213914163877964163 * (elementaryCharge * elementaryCharge) = planck := by
  norm_num [planck, elementaryCharge]

/-- Φ₀: magnetic flux quantum [Wb]; derived: planck / (2 * elementaryCharge). -/
def fluxQuantum : ℚ := planck / (2 * elementaryCharge)

theorem fluxQuantum_value : fluxQuantum = (44173801 : ℚ) / 21362355120000000000000 := by
  norm_num [fluxQuantum, planck, elementaryCharge]

theorem fluxQuantum_derivation : (44173801 : ℚ) / 21362355120000000000000 * (2 * elementaryCharge) = planck := by
  norm_num [planck, elementaryCharge]

/-- G₀: conductance quantum [S]; derived: 2 * elementaryCharge * elementaryCharge / planck. -/
def conductanceQuantum : ℚ := 2 * elementaryCharge * elementaryCharge / planck

theorem conductanceQuantum_value : conductanceQuantum = (213914163877964163 : ℚ) / 2760862562500000000000 := by
  norm_num [conductanceQuantum, planck, elementaryCharge]

theorem conductanceQuantum_derivation : (213914163877964163 : ℚ) / 2760862562500000000000 * (planck) = 2 * elementaryCharge * elementaryCharge := by
  norm_num [planck, elementaryCharge]

/-- α: fine-structure constant [1]; measured, cited from CODATA2022. -/
def fineStructure : ℚ := (72973525643 : ℚ) / 10000000000000
/-- Standard uncertainty of α (CODATA2022). -/
def fineStructureUncertainty : ℚ := (11 : ℚ) / 10000000000000

/-- ε₀: vacuum electric permittivity [F m⁻¹]; derived: elementaryCharge * elementaryCharge / (2 * fineStructure * planck * speedOfLight). -/
def vacuumPermittivity : ℚ := elementaryCharge * elementaryCharge / (2 * fineStructure * planck * speedOfLight)

theorem vacuumPermittivity_value : vacuumPermittivity = (213914163877964163 : ℚ) / 24159659615848077226571442350 := by
  norm_num [vacuumPermittivity, speedOfLight, planck, elementaryCharge, fineStructure]

theorem vacuumPermittivity_derivation : (213914163877964163 : ℚ) / 24159659615848077226571442350 * (2 * fineStructure * planck * speedOfLight) = elementaryCharge * elementaryCharge := by
  norm_num [speedOfLight, planck, elementaryCharge, fineStructure]

/-- ε₀ derived here lies within the CODATA2022 value's standard uncertainty. -/
theorem vacuumPermittivity_within_CODATA2022 :
    |vacuumPermittivity - (22135469547 : ℚ) / 2500000000000000000000| ≤ (7 : ℚ) / 5000000000000000000000 := by
  rw [vacuumPermittivity_value, abs_le]
  constructor <;> norm_num

/-- μ₀: vacuum magnetic permeability [N A⁻²]; derived: 2 * fineStructure * planck / (elementaryCharge * elementaryCharge * speedOfLight). -/
def vacuumPermeability : ℚ := 2 * fineStructure * planck / (elementaryCharge * elementaryCharge * speedOfLight)

theorem vacuumPermeability_value : vacuumPermeability = (11512564285793853725 : ℚ) / 9161407569998526923097522 := by
  norm_num [vacuumPermeability, speedOfLight, planck, elementaryCharge, fineStructure]

theorem vacuumPermeability_derivation : (11512564285793853725 : ℚ) / 9161407569998526923097522 * (elementaryCharge * elementaryCharge * speedOfLight) = 2 * fineStructure * planck := by
  norm_num [speedOfLight, planck, elementaryCharge, fineStructure]

/-- μ₀ derived here lies within the CODATA2022 value's standard uncertainty. -/
theorem vacuumPermeability_within_CODATA2022 :
    |vacuumPermeability - (125663706127 : ℚ) / 100000000000000000| ≤ (1 : ℚ) / 5000000000000000 := by
  rw [vacuumPermeability_value, abs_le]
  constructor <;> norm_num

/-- w_n: non-evaporable water at complete hydration (Powers' model) [kg per kg cement]; cited: D. P. Bentz, E. F. Irassar, B. E. Bucher and W. J. Weiss, Limestone Fillers Conserve Cement, Part 1. -/
def nonEvaporableWater : ℚ := (23 : ℚ) / 100

/-- w_cs: chemical shrinkage at complete hydration (Powers' model) [kg water per kg cement]; cited: D. P. Bentz, E. F. Irassar, B. E. Bucher and W. J. Weiss, Limestone Fillers Conserve Cement, Part 1. -/
def chemicalShrinkage : ℚ := (8 : ℚ) / 125

/-- w_g: gel water at complete hydration (Powers' model) [kg per kg cement]; cited: D. P. Bentz, E. F. Irassar, B. E. Bucher and W. J. Weiss, Limestone Fillers Conserve Cement, Part 1. -/
def gelWater : ℚ := (19 : ℚ) / 100

/-- ρ_w: density of water assigned in Powers' model [kg m⁻³]; cited: D. P. Bentz, E. F. Irassar, B. E. Bucher and W. J. Weiss, Limestone Fillers Conserve Cement, Part 1. -/
def waterDensity : ℚ := (1000 : ℚ)

/-- ρ_c: density of cement assigned in Powers' model [kg m⁻³]; cited: D. P. Bentz, E. F. Irassar, B. E. Bucher and W. J. Weiss, Limestone Fillers Conserve Cement, Part 1. -/
def cementDensity : ℚ := (3150 : ℚ)

/-- (w/c)*: water-cement ratio at which sealed paste just hydrates completely [1]; derived: nonEvaporableWater + gelWater. -/
def criticalWcSealed : ℚ := nonEvaporableWater + gelWater

theorem criticalWcSealed_value : criticalWcSealed = (21 : ℚ) / 50 := by
  norm_num [criticalWcSealed, nonEvaporableWater, gelWater]

/-- (w/c)_s: water-cement ratio below which space limits complete hydration [1]; derived: nonEvaporableWater + gelWater - chemicalShrinkage. -/
def criticalWcSpace : ℚ := nonEvaporableWater + gelWater - chemicalShrinkage

theorem criticalWcSpace_value : criticalWcSpace = (89 : ℚ) / 250 := by
  norm_num [criticalWcSpace, nonEvaporableWater, chemicalShrinkage, gelWater]

/-- ρ_c/ρ_w: specific gravity of cement in Powers' model [1]; derived: cementDensity / waterDensity. -/
def densityRatio : ℚ := cementDensity / waterDensity

theorem densityRatio_value : densityRatio = (63 : ℚ) / 20 := by
  norm_num [densityRatio, waterDensity, cementDensity]

theorem densityRatio_derivation : (63 : ℚ) / 20 * (waterDensity) = cementDensity := by
  norm_num [waterDensity, cementDensity]

/-- v_cs: chemical-shrinkage volume per volume of cement reacted [1]; derived: chemicalShrinkage * densityRatio. -/
def shrinkageVolume : ℚ := chemicalShrinkage * densityRatio

theorem shrinkageVolume_value : shrinkageVolume = (126 : ℚ) / 625 := by
  norm_num [shrinkageVolume, chemicalShrinkage, waterDensity, cementDensity, densityRatio]

/-- v_gw: gel-water volume per volume of cement reacted [1]; derived: gelWater * densityRatio. -/
def gelWaterVolume : ℚ := gelWater * densityRatio

theorem gelWaterVolume_value : gelWaterVolume = (1197 : ℚ) / 2000 := by
  norm_num [gelWaterVolume, gelWater, waterDensity, cementDensity, densityRatio]

/-- v_cw: capillary water consumed per volume of cement reacted [1]; derived: criticalWcSealed * densityRatio. -/
def capillaryConsumption : ℚ := criticalWcSealed * densityRatio

theorem capillaryConsumption_value : capillaryConsumption = (1323 : ℚ) / 1000 := by
  norm_num [capillaryConsumption, nonEvaporableWater, gelWater, waterDensity, cementDensity, criticalWcSealed, densityRatio]

/-- w_n − w_cs: water bound into gel solids per mass of cement reacted [kg per kg cement]; derived: nonEvaporableWater - chemicalShrinkage. -/
def boundWater : ℚ := nonEvaporableWater - chemicalShrinkage

theorem boundWater_value : boundWater = (83 : ℚ) / 500 := by
  norm_num [boundWater, nonEvaporableWater, chemicalShrinkage]

/-- v_b: volume of water bound into gel solids per volume of cement reacted [1]; derived: boundWater * densityRatio. -/
def boundWaterVolume : ℚ := boundWater * densityRatio

theorem boundWaterVolume_value : boundWaterVolume = (5229 : ℚ) / 10000 := by
  norm_num [boundWaterVolume, nonEvaporableWater, chemicalShrinkage, waterDensity, cementDensity, densityRatio, boundWater]

/-- v_gs: gel-solids volume per volume of cement reacted [1]; derived: 1 + boundWaterVolume. -/
def gelSolidsVolume : ℚ := 1 + boundWaterVolume

theorem gelSolidsVolume_value : gelSolidsVolume = (15229 : ℚ) / 10000 := by
  norm_num [gelSolidsVolume, nonEvaporableWater, chemicalShrinkage, waterDensity, cementDensity, densityRatio, boundWater, boundWaterVolume]

/-- A: intrinsic strength of the gel in Powers' gel-space law [MPa]; cited: T. C. Powers, Structure and Physical Properties of Hardened Portland Cement Paste, Journal of the American Ceramic Society (1958), doi. -/
def powersGelStrength : ℚ := (234 : ℚ)

/-- n: exponent of Powers' gel-space law [1]; cited: T. C. Powers, Structure and Physical Properties of Hardened Portland Cement Paste, Journal of the American Ceramic Society (1958), doi. -/
def powersGelExponent : ℚ := (3 : ℚ)

/-- Q_C3S: heat released by complete hydration of tricalcium silicate (alite) [J/g]; measured, cited from Taylor1997. -/
def hydrationHeatC3S : ℚ := (517 : ℚ)
/-- Standard uncertainty of Q_C3S (Taylor1997). -/
def hydrationHeatC3SUncertainty : ℚ := (13 : ℚ)

/-- Q_C2S: heat released by complete hydration of dicalcium silicate (belite) [J/g]; cited: H. F. W. Taylor, Cement Chemistry, Thomas Telford, London (1997), enthalpies of complete hydration of the clinker phases as tabulated by P. Stutzman, S. Leigh and K. Dolly, Statistical Modeling Cement Heat of Hydration (NIST), Table 1. -/
def hydrationHeatC2S : ℚ := (262 : ℚ)

/-- Q_C3A,AFm: heat released by complete hydration of tricalcium aluminate to AFm [J/g]; cited: H. F. W. Taylor, Cement Chemistry, Thomas Telford, London (1997), enthalpies of complete hydration of the clinker phases as tabulated by P. Stutzman, S. Leigh and K. Dolly, Statistical Modeling Cement Heat of Hydration (NIST), Table 1. -/
def hydrationHeatC3AtoAFm : ℚ := (1144 : ℚ)

/-- Q_C3A,AFt: heat released by complete hydration of tricalcium aluminate to AFt [J/g]; cited: H. F. W. Taylor, Cement Chemistry, Thomas Telford, London (1997), enthalpies of complete hydration of the clinker phases as tabulated by P. Stutzman, S. Leigh and K. Dolly, Statistical Modeling Cement Heat of Hydration (NIST), Table 1. -/
def hydrationHeatC3AtoAFt : ℚ := (1672 : ℚ)

/-- Q_C4AF: heat released by complete hydration of tetracalcium aluminoferrite [J/g]; cited: H. F. W. Taylor, Cement Chemistry, Thomas Telford, London (1997), enthalpies of complete hydration of the clinker phases as tabulated by P. Stutzman, S. Leigh and K. Dolly, Statistical Modeling Cement Heat of Hydration (NIST), Table 1. -/
def hydrationHeatC4AF : ℚ := (418 : ℚ)

/-- Q_hyd: heat of complete hydration of a portland cement (model default) [J/g]; policy (a model choice, not a constant): a cement's heat of complete hydration is the mass-weighted sum of its phases' heats, so for a clinker of the four phases it lies between the least and the greatest phase heat; 450 is the gate's default for an unspecified portland cement. -/
def hydrationHeatDefault : ℚ := (450 : ℚ)

/-- The choice lies in its range [hydrationHeatC2S, hydrationHeatC3AtoAFt]. -/
theorem hydrationHeatDefault_in_range : hydrationHeatC2S ≤ hydrationHeatDefault ∧ hydrationHeatDefault ≤ hydrationHeatC3AtoAFt := by
  norm_num [hydrationHeatDefault, hydrationHeatC2S, hydrationHeatC3AtoAFt]

end UMST.Constants.SI
