-- SPDX-FileCopyrightText: 2026 Santosh Prabhu Shenbagamoorthy and Santhosh Shyamsundar
-- SPDX-License-Identifier: MIT
/-
  Generated by scripts/gen_constants.py from constants/constants.json; edit the table, not this file.

  The constants of the UMST ecosystem as exact rationals: the seven defining constants of the SI (cited),
  cited measurements with their standard uncertainty, and constants derived from them, each with its exact
  value and its defining equation proved by computation. `Constants.SIBridge` identifies these values with
  the real-valued constants of the Landauer chain and states the laws that carry the second law.
-/

import Mathlib.Tactic.NormNum
import Mathlib.Algebra.Order.Group.Abs

namespace UMST.Constants.SI

/-- ΔνCs: caesium-133 hyperfine transition frequency [Hz]; cited: BIPM, The International System of Units (SI), 9th edition (2019), Table 1. -/
def caesiumHyperfineFrequency : ℚ := (9192631770 : ℚ)

/-- c: speed of light in vacuum [m s⁻¹]; cited: BIPM, The International System of Units (SI), 9th edition (2019), Table 1. -/
def speedOfLight : ℚ := (299792458 : ℚ)

/-- h: Planck constant [J s]; cited: BIPM, The International System of Units (SI), 9th edition (2019), Table 1. -/
def planck : ℚ := (132521403 : ℚ) / 200000000000000000000000000000000000000000

/-- e: elementary charge [C]; cited: BIPM, The International System of Units (SI), 9th edition (2019), Table 1. -/
def elementaryCharge : ℚ := (801088317 : ℚ) / 5000000000000000000000000000

/-- k_B: Boltzmann constant [J K⁻¹]; cited: BIPM, The International System of Units (SI), 9th edition (2019), Table 1. -/
def boltzmann : ℚ := (1380649 : ℚ) / 100000000000000000000000000000

/-- N_A: Avogadro constant [mol⁻¹]; cited: BIPM, The International System of Units (SI), 9th edition (2019), Table 1. -/
def avogadro : ℚ := (602214076000000000000000 : ℚ)

/-- K_cd: luminous efficacy of 540 THz radiation [lm W⁻¹]; cited: BIPM, The International System of Units (SI), 9th edition (2019), Table 1. -/
def luminousEfficacy : ℚ := (683 : ℚ)

/-- R: molar gas constant [J mol⁻¹ K⁻¹]; derived: avogadro * boltzmann. -/
def gasConstant : ℚ := avogadro * boltzmann

theorem gasConstant_value : gasConstant = (207861565453831 : ℚ) / 25000000000000 := by
  norm_num [gasConstant, boltzmann, avogadro]

/-- F: Faraday constant [C mol⁻¹]; derived: avogadro * elementaryCharge. -/
def faraday : ℚ := avogadro * elementaryCharge

theorem faraday_value : faraday = (120606665154137523 : ℚ) / 1250000000000 := by
  norm_num [faraday, elementaryCharge, avogadro]

/-- c²: mass–energy conversion factor [m² s⁻²]; derived: speedOfLight * speedOfLight. -/
def speedOfLightSquared : ℚ := speedOfLight * speedOfLight

theorem speedOfLightSquared_value : speedOfLightSquared = (89875517873681764 : ℚ) := by
  norm_num [speedOfLightSquared, speedOfLight]

/-- K_J: Josephson constant [Hz V⁻¹]; derived: 2 * elementaryCharge / planck. -/
def josephson : ℚ := 2 * elementaryCharge / planck

theorem josephson_value : josephson = (21362355120000000000000 : ℚ) / 44173801 := by
  norm_num [josephson, planck, elementaryCharge]

theorem josephson_derivation : (21362355120000000000000 : ℚ) / 44173801 * (planck) = 2 * elementaryCharge := by
  norm_num [planck, elementaryCharge]

/-- R_K: von Klitzing constant [Ω]; derived: planck / (elementaryCharge * elementaryCharge). -/
def vonKlitzing : ℚ := planck / (elementaryCharge * elementaryCharge)

theorem vonKlitzing_value : vonKlitzing = (5521725125000000000000 : ℚ) / 213914163877964163 := by
  norm_num [vonKlitzing, planck, elementaryCharge]

theorem vonKlitzing_derivation : (5521725125000000000000 : ℚ) / 213914163877964163 * (elementaryCharge * elementaryCharge) = planck := by
  norm_num [planck, elementaryCharge]

/-- Φ₀: magnetic flux quantum [Wb]; derived: planck / (2 * elementaryCharge). -/
def fluxQuantum : ℚ := planck / (2 * elementaryCharge)

theorem fluxQuantum_value : fluxQuantum = (44173801 : ℚ) / 21362355120000000000000 := by
  norm_num [fluxQuantum, planck, elementaryCharge]

theorem fluxQuantum_derivation : (44173801 : ℚ) / 21362355120000000000000 * (2 * elementaryCharge) = planck := by
  norm_num [planck, elementaryCharge]

/-- G₀: conductance quantum [S]; derived: 2 * elementaryCharge * elementaryCharge / planck. -/
def conductanceQuantum : ℚ := 2 * elementaryCharge * elementaryCharge / planck

theorem conductanceQuantum_value : conductanceQuantum = (213914163877964163 : ℚ) / 2760862562500000000000 := by
  norm_num [conductanceQuantum, planck, elementaryCharge]

theorem conductanceQuantum_derivation : (213914163877964163 : ℚ) / 2760862562500000000000 * (planck) = 2 * elementaryCharge * elementaryCharge := by
  norm_num [planck, elementaryCharge]

/-- α: fine-structure constant [1]; measured, cited from CODATA2022. -/
def fineStructure : ℚ := (72973525643 : ℚ) / 10000000000000
/-- Standard uncertainty of α (CODATA2022). -/
def fineStructureUncertainty : ℚ := (11 : ℚ) / 10000000000000

/-- ε₀: vacuum electric permittivity [F m⁻¹]; derived: elementaryCharge * elementaryCharge / (2 * fineStructure * planck * speedOfLight). -/
def vacuumPermittivity : ℚ := elementaryCharge * elementaryCharge / (2 * fineStructure * planck * speedOfLight)

theorem vacuumPermittivity_value : vacuumPermittivity = (213914163877964163 : ℚ) / 24159659615848077226571442350 := by
  norm_num [vacuumPermittivity, speedOfLight, planck, elementaryCharge, fineStructure]

theorem vacuumPermittivity_derivation : (213914163877964163 : ℚ) / 24159659615848077226571442350 * (2 * fineStructure * planck * speedOfLight) = elementaryCharge * elementaryCharge := by
  norm_num [speedOfLight, planck, elementaryCharge, fineStructure]

/-- ε₀ derived here lies within the CODATA2022 value's standard uncertainty. -/
theorem vacuumPermittivity_within_CODATA2022 :
    |vacuumPermittivity - (22135469547 : ℚ) / 2500000000000000000000| ≤ (7 : ℚ) / 5000000000000000000000 := by
  rw [vacuumPermittivity_value, abs_le]
  constructor <;> norm_num

/-- μ₀: vacuum magnetic permeability [N A⁻²]; derived: 2 * fineStructure * planck / (elementaryCharge * elementaryCharge * speedOfLight). -/
def vacuumPermeability : ℚ := 2 * fineStructure * planck / (elementaryCharge * elementaryCharge * speedOfLight)

theorem vacuumPermeability_value : vacuumPermeability = (11512564285793853725 : ℚ) / 9161407569998526923097522 := by
  norm_num [vacuumPermeability, speedOfLight, planck, elementaryCharge, fineStructure]

theorem vacuumPermeability_derivation : (11512564285793853725 : ℚ) / 9161407569998526923097522 * (elementaryCharge * elementaryCharge * speedOfLight) = 2 * fineStructure * planck := by
  norm_num [speedOfLight, planck, elementaryCharge, fineStructure]

/-- μ₀ derived here lies within the CODATA2022 value's standard uncertainty. -/
theorem vacuumPermeability_within_CODATA2022 :
    |vacuumPermeability - (125663706127 : ℚ) / 100000000000000000| ≤ (1 : ℚ) / 5000000000000000 := by
  rw [vacuumPermeability_value, abs_le]
  constructor <;> norm_num

end UMST.Constants.SI
