-- SPDX-FileCopyrightText: 2026 Santosh Prabhu Shenbagamoorthy and Santhosh Shyamsundar
-- SPDX-License-Identifier: MIT
-- Generated by scripts/gen_constants.py from constants/constants.json; edit the table, not this file.
-- |
-- The second-law bounds of the constants table (twin of Lean/Constants/Bounds.lean): exact endpoints, the
-- theorem that proves each bound, and 'admits'. A bound fixes no value; the value stays cited, measured or
-- chosen. 'boundChecks' lists each bound on a table row against the row's exact value.
module UMST.Constants.Bounds where

import Data.Ratio ((%))

-- | One endpoint: the exact value and whether the endpoint itself is excluded.
data Endpoint = Endpoint { endpointAt :: Rational, endpointStrict :: Bool } deriving (Eq, Show)

-- | A second-law bound: the interval a quantity must lie in and the theorem (Lean name) that proves it.
data Bound = Bound
  { boundId :: String
  , boundSymbol :: String
  , boundUnit :: Maybe String
  , boundLower :: Maybe Endpoint
  , boundUpper :: Maybe Endpoint
  , boundTheorem :: String
  , boundLanguages :: [String]
  } deriving (Eq, Show)

-- | Whether a value lies in the bound.
admits :: Bound -> Rational -> Bool
admits b v = maybe True above (boundLower b) && maybe True below (boundUpper b)
  where
    above (Endpoint a s) = if s then a < v else a <= v
    below (Endpoint a s) = if s then v < a else v <= a

-- | E: an elastic modulus holding a body at a nonzero stress (Young's modulus in uniaxial stress, the shear modulus
-- in pure shear) [Pa] lies in (0, ∞); proved by UMST.Constants.SecondLawElastic.relaxation_modulus_pos
-- (second_law_bound.modulus_pos: a body held at stress σ ≠ 0 by a modulus E ≠ 0 stores σ²/(2E); its passive
-- relaxation under the second law forces E > 0 (Agda: the stored energy ψ is given by 2·E·ψ = σ², σ² a positive
-- rational, and E ≠ 0 follows)).
elasticModulusPositive :: Bound
elasticModulusPositive = Bound "elasticModulusPositive" "E" (Just "Pa") (Just (Endpoint (0 % 1) True)) Nothing
  "UMST.Constants.SecondLawElastic.relaxation_modulus_pos" ["lean", "coq", "agda", "haskell"]

-- | k: the stiffness of a mode storing ½·k·s² [any unit] lies in [0, ∞); proved by
-- UMST.Constants.SecondLawElastic.relaxation_stiffness_nonneg (second_law_bound.stiffness_nonneg: a mode storing
-- ½·k·s² (s ≠ 0) whose passive relaxation to the natural state obeys the second law (transition case) has k ≥ 0
-- (Agda: the squared strain enters as a positive rational q)).
quadraticStiffnessNonneg :: Bound
quadraticStiffnessNonneg = Bound "quadraticStiffnessNonneg" "k" Nothing (Just (Endpoint (0 % 1) False)) Nothing
  "UMST.Constants.SecondLawElastic.relaxation_stiffness_nonneg" ["lean", "coq", "agda", "haskell"]

-- | ν: the Poisson ratio of an isotropic solid with 3K + G > 0 [1] lies in [-1, 1/2]; proved by
-- UMST.Constants.SecondLawElastic.isotropic_poisson_bounds (second_law_bound.isotropic_poisson: an isotropic
-- solid storing ½·K·e² + ½·G·γ² relaxing passively under the second law from every volumetric strain and shear,
-- with 3K + G > 0, has −1 ≤ ν ≤ 1/2 for ν = (3K − 2G)/(2(3K + G)) (Agda: the denominator cleared, −2(3K + G) ≤ 3K
-- − 2G ≤ 3K + G)).
isotropicPoissonRatio :: Bound
isotropicPoissonRatio = Bound "isotropicPoissonRatio" "ν" (Just "1") (Just (Endpoint (-1 % 1) False)) (Just (Endpoint (1 % 2) False))
  "UMST.Constants.SecondLawElastic.isotropic_poisson_bounds" ["lean", "coq", "agda", "haskell"]

-- | E: Young's modulus 9KG/(3K + G) of an isotropic solid with 3K + G > 0 [Pa] lies in [0, ∞); proved by
-- UMST.Constants.SecondLawElastic.isotropic_young_nonneg (second_law_bound.isotropic_young: under the same
-- relaxation Young's modulus E = 9KG/(3K + G) is nonnegative (Agda: the denominator cleared, 9·K·G ≥ 0)).
isotropicYoungModulusNonneg :: Bound
isotropicYoungModulusNonneg = Bound "isotropicYoungModulusNonneg" "E" (Just "Pa") (Just (Endpoint (0 % 1) False)) Nothing
  "UMST.Constants.SecondLawElastic.isotropic_young_nonneg" ["lean", "coq", "agda", "haskell"]

-- | G∞: the relaxed modulus of a standard linear solid (it is also at most the instantaneous modulus G∞ + G₁) [Pa]
-- lies in [0, ∞); proved by UMST.Constants.SecondLawElastic.sls_relaxed_le_instantaneous
-- (second_law_bound.sls_relaxed: a standard linear solid storing ½·G∞·ε² + ½·G₁·ξ² relaxing passively under the
-- second law from every total and arm strain has 0 ≤ G∞ ≤ G∞ + G₁ = G₀).
relaxedModulusNonneg :: Bound
relaxedModulusNonneg = Bound "relaxedModulusNonneg" "G∞" (Just "Pa") (Just (Endpoint (0 % 1) False)) Nothing
  "UMST.Constants.SecondLawElastic.sls_relaxed_le_instantaneous" ["lean", "coq", "agda", "haskell"]

-- | c: a dissipation coefficient c in a dissipated energy c·q, q > 0 [any unit] lies in [0, ∞); proved by
-- UMST.Constants.SecondLawDissipation.dissipation_coefficient_nonneg (second_law_bound.dissipation_coefficient: a
-- passive step dissipating c·q (q > 0) out of the free energy obeys the second law (transition case) only when c
-- ≥ 0).
dissipationCoefficientNonneg :: Bound
dissipationCoefficientNonneg = Bound "dissipationCoefficientNonneg" "c" Nothing (Just (Endpoint (0 % 1) False)) Nothing
  "UMST.Constants.SecondLawDissipation.dissipation_coefficient_nonneg" ["lean", "coq", "agda", "haskell"]

-- | η: a dashpot viscosity [Pa s] lies in [0, ∞); proved by UMST.Constants.SecondLawDissipation.viscosity_nonneg
-- (second_law_bound.viscosity: a dashpot at rate r ≠ 0 over dt > 0 dissipating η·r²·dt obeys the second law only
-- when η ≥ 0 (Agda: r² enters as a positive rational q)).
viscosityNonneg :: Bound
viscosityNonneg = Bound "viscosityNonneg" "η" (Just "Pa s") (Just (Endpoint (0 % 1) False)) Nothing
  "UMST.Constants.SecondLawDissipation.viscosity_nonneg" ["lean", "coq", "agda", "haskell"]

-- | τ₀: the yield stress of a Bingham fluid [Pa] lies in [0, ∞); proved by
-- UMST.Constants.SecondLawDissipation.bingham_nonneg (second_law_bound.bingham: a Bingham fluid dissipating
-- (τ₀·|r| + η_p·r²)·dt that obeys the second law at every rate has τ₀ ≥ 0 and η_p ≥ 0 (Agda: at every positive
-- rate, where |r| = r)).
binghamYieldStressNonneg :: Bound
binghamYieldStressNonneg = Bound "binghamYieldStressNonneg" "τ₀" (Just "Pa") (Just (Endpoint (0 % 1) False)) Nothing
  "UMST.Constants.SecondLawDissipation.bingham_nonneg" ["lean", "coq", "agda", "haskell"]

-- | η_p: the plastic viscosity of a Bingham fluid [Pa s] lies in [0, ∞); proved by
-- UMST.Constants.SecondLawDissipation.bingham_nonneg (second_law_bound.bingham: a Bingham fluid dissipating
-- (τ₀·|r| + η_p·r²)·dt that obeys the second law at every rate has τ₀ ≥ 0 and η_p ≥ 0 (Agda: at every positive
-- rate, where |r| = r)).
binghamPlasticViscosityNonneg :: Bound
binghamPlasticViscosityNonneg = Bound "binghamPlasticViscosityNonneg" "η_p" (Just "Pa s") (Just (Endpoint (0 % 1) False)) Nothing
  "UMST.Constants.SecondLawDissipation.bingham_nonneg" ["lean", "coq", "agda", "haskell"]

-- | E″: the loss modulus of a harmonic strain cycle [Pa] lies in [0, ∞); proved by
-- UMST.Constants.SecondLawDissipation.lossModulus_nonneg (second_law_bound.loss_modulus: a harmonic strain cycle
-- dissipating π·E″·ε₀² (ε₀ ≠ 0) obeys the second law only when E″ ≥ 0, and then E″/E′ ≥ 0 for E′ > 0 (Coq, Agda:
-- the cycle measure π·ε₀² enters as a positive rational q)).
lossModulusNonneg :: Bound
lossModulusNonneg = Bound "lossModulusNonneg" "E″" (Just "Pa") (Just (Endpoint (0 % 1) False)) Nothing
  "UMST.Constants.SecondLawDissipation.lossModulus_nonneg" ["lean", "coq", "agda", "haskell"]

-- | e: a coefficient of restitution e ≥ 0 of a passive impact [1] lies in (−∞, 1]; proved by
-- UMST.ConvexPhiChannels.restitution_le_one (second_law_bound.restitution: a passive impact with free energy
-- ½·μ·v² before and ½·μ·(e·v)² after that obeys the second law (transition case) has e ≤ 1 for e ≥ 0 and μ·v² > 0
-- (Agda: μ·v² enters as a positive rational m)).
restitutionAtMostOne :: Bound
restitutionAtMostOne = Bound "restitutionAtMostOne" "e" (Just "1") Nothing (Just (Endpoint (1 % 1) False))
  "UMST.ConvexPhiChannels.restitution_le_one" ["lean", "coq", "agda", "haskell"]

-- | Every bound, in table order.
bounds :: [Bound]
bounds = [elasticModulusPositive, quadraticStiffnessNonneg, isotropicPoissonRatio, isotropicYoungModulusNonneg, relaxedModulusNonneg, dissipationCoefficientNonneg, viscosityNonneg, binghamYieldStressNonneg, binghamPlasticViscosityNonneg, lossModulusNonneg, restitutionAtMostOne]

-- | Each bound on a table row against the row's exact value.
boundChecks :: [(String, Bool)]
boundChecks = []
